# Railway configuration for multi-service deployment
# This tells Railway to deploy all 3 services separately

# Backend Service (Spring Boot)
[[service]]
name = "backend"
source = "."
buildCommand = "mvn clean package -DskipTests"
startCommand = "java -jar target/credit_score_sys-0.0.1-SNAPSHOT.jar"
watchPaths = ["src/**", "pom.xml"]

# ML Service (Python/Flask)
[[service]]
name = "ml-service"
source = "ml_service"
buildCommand = "pip install -r requirements.txt"
startCommand = "python app.py"
watchPaths = ["ml_service/**"]

# Frontend (React/Vite)
[[service]]
name = "frontend"
source = "frontend"
buildCommand = "npm install && npm run build"
startCommand = "npx serve -s dist -l $PORT"
watchPaths = ["frontend/**"]
