services:
  # Spring Boot Backend
  - type: web
    name: scorebridge-backend
    env: java
    buildCommand: mvn clean package -DskipTests
    startCommand: java -jar target/credit_score_sys-0.0.1-SNAPSHOT.jar
    envVars:
      - key: SERVER_PORT
        value: 8080
      - key: ML_SERVICE_URL
        fromService:
          type: web
          name: scorebridge-ml
          envVarKey: RENDER_EXTERNAL_URL
      - key: JWT_SECRET
        generateValue: true
      - key: SPRING_DATASOURCE_URL
        value: jdbc:h2:mem:scorebridge
      - key: CORS_ALLOWED_ORIGINS
        fromService:
          type: web
          name: scorebridge-frontend
          envVarKey: RENDER_EXTERNAL_URL
    healthCheckPath: /actuator/health

  # Python ML Service
  - type: web
    name: scorebridge-ml
    env: python
    rootDir: ml_service
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: PORT
        value: 5000
      - key: FLASK_ENV
        value: production
    healthCheckPath: /health

  # React Frontend (Static Site)
  - type: web
    name: scorebridge-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        fromService:
          type: web
          name: scorebridge-backend
          envVarKey: RENDER_EXTERNAL_URL
